// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migration.DataAccess;

#nullable disable

namespace Migration.DataAccess.Migrations.UserOldDb
{
    [DbContext(typeof(UserOldDbContext))]
    [Migration("20251022134912_SeedInitialUsers")]
    partial class SeedInitialUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Migration.DataAccess.Model.UserOld", b =>
                {
                    b.Property<int>("LegacyUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegacyUserId"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMigrated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegacyEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LegacyUserId");

                    b.ToTable("UsersOld");

                    b.HasData(
                        new
                        {
                            LegacyUserId = 1,
                            DocumentType = "FACTURE",
                            FirstName = "Mario",
                            IsMigrated = false,
                            LastName = "Bianchi",
                            LegacyEmailAddress = "mario.bianchi@email.com",
                            Status = "ATTIVO"
                        },
                        new
                        {
                            LegacyUserId = 2,
                            DocumentType = "FACTURE",
                            FirstName = "Marco",
                            IsMigrated = false,
                            LastName = "Verdi",
                            LegacyEmailAddress = "marco.verdi@email.com",
                            Status = "ATTIVO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
